name: Asi

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: playlist-update
  cancel-in-progress: true

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download and Update M3U Links
        run: |
          # ഡൗൺലോഡ് ചെയ്ത് Asi.m3u ഫയൽ അപ്ഡേറ്റ് ചെയ്യുന്നു
          curl -L "https://t.ayush848694.workers.dev/" -o Asi.m3u

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Asi.m3u ഫയൽ സ്റ്റേജ് ചെയ്യുന്നു
          git add Asi.m3u
          
          if git diff --staged --quiet; then
            echo "പ്ലേലിസ്റ്റിൽ പുതിയ മാറ്റങ്ങൾ ഒന്നും തന്നെയില്ല."
          else
            git commit -m "chore: update Asi.m3u with all latest links"
            git pull --rebase origin main
            git push origin main
          fi
