name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream
        run: git remote add upstream https://github.com/joiptv/jojo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: git merge upstream/main --no-edit

      - name: Push Changes
        run: git push origin HEAD:main